app:
  jwt:
    secret: ${JWT_SECRET}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    show-sql: false

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}

  flyway:
    clean-disabled: true   # nunca permitir flyway clean em produção

logging:
  level:
    root: INFO
    com.vivo4redes.syscor: INFO

management:
  endpoint:
    health:
      show-details: never