-- Migration V15: Adiciona novos campos de endereço/documentos e ajusta limites de colunas
ALTER TABLE clientes
    ADD COLUMN IF NOT EXISTS rg_ie VARCHAR(100),
    ADD COLUMN IF NOT EXISTS uf VARCHAR(10),
    ADD COLUMN IF NOT EXISTS cidade VARCHAR(255),
    ADD COLUMN IF NOT EXISTS endereco VARCHAR(500),
    ADD COLUMN IF NOT EXISTS complemento VARCHAR(255),
    ADD COLUMN IF NOT EXISTS bairro VARCHAR(255),
    ADD COLUMN IF NOT EXISTS cep VARCHAR(20);

ALTER TABLE clientes
ALTER COLUMN nome TYPE VARCHAR(255),
    ALTER COLUMN cpf_cnpj DROP NOT NULL,
    ALTER COLUMN cpf_cnpj TYPE VARCHAR(50),
    ALTER COLUMN email TYPE VARCHAR(255),
    ALTER COLUMN telefone TYPE VARCHAR(50);